### PR TITLE
cm3s io: camera v2: Modify the control method of pwdn_gpio

### PR DESCRIPTION
**Pull request by vamrs-feng**
The original control method is invalid in the 5.10 kernel driver, and the regulator is used to realize it.

### CODE REVIEW

**Review by RadxaYuntian — COMMENTED** [review]
在新内核上测试过么？

**Comment by vamrs-feng** [comment]
对，针对5.10 rkr4.1调的。

**Comment by vamrs-feng** [comment]
稍等，我先俩个都测一下吧，只测一个。

**Comment by vamrs-feng** [comment]
可以了

**Review by RadxaYuntian — APPROVED** [review]

**Pull request merged**
